---
abstract: unknown
author:
  - 'Harun Delgado <hdp@nurmol.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Fast
no_index:
  directory:
    - t
    - inc
requires:
  DBIx::Connector: '0.53'
  Moo: '1'
  perl: '5.006'
version: '0.09'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
