name: Unit tests

on:
  workflow_call:
    inputs:
      perl_version:
        required: false
        type: string
        default: "['5.38']"
      os:
        required: false
        type: string
        default: "['windows-latest', 'macos-latest', 'ubuntu-latest','self-hosted']"

jobs:
  testing:
    runs-on: self-hosted
    strategy:
      matrix:
	os: ["macos-latest"]
	perl: ["5.38"]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Perl version
        run: perl -V
      - name: Install modules
        run: cpanm --notest --installdeps .
      - name: Run tests
        run: prove -lv t
      - name: Archive CPAN logs on Windows
        if: ${{ failure() && matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: cpan_log
          path: C:\Users\RUNNER~1\.cpanm\work\*\build.log
          retention-days: 5
      - name: Archive CPAN logs on Unix
        if: ${{ failure() && matrix.os != 'windows-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: cpan_log
          path: /home/runner/.cpanm/work/*/build.log
          retention-days: 5
