name: linux
run-name: ${{ github.actor }} is run prove on Linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        codename:
          - buster
        perl-version:
          - '5.16'
          - '5.18'
          - '5.20'
          - '5.22'
          - '5.30'
          - '5.36'
          - '5.40'
    container:
      image: perl:${{ matrix.perl-version }}-${{ matrix.codename }}
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: |
          cpanm -n --installdeps .
          cpanm -n TAP::Formatter::GitHubActions
      - name: Run tests
        run: prove --merge --formatter TAP::Formatter::GitHubActions -l t/
