name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  runs-on: self-hosted
  build:
    uses: PerlToolsTeam/github_workflows/.github/workflows/cpan-test.yml@main