name: CI

runs-on: self-hosted

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    uses: SeHarrys/dbix-fast/.github/workflows/cpan-test.yml@main